FROM ubuntu:18.04
LABEL maintainer="Zhakaris Margarita"
ENV TZ=Europe/Moscow  
     
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone  
RUN apt-get update  
RUN apt-get install qt5-default -y  
RUN apt-get install qtbase5-dev -y  
RUN apt-get install qt5-qmake  
RUN apt-get install build-essential -y . 

WORKDIR /root/
RUN mkdir MyProj_221_331_Zhakaris
WORKDIR /root/MyProj_221_331_Zhakaris/
COPY *.cpp /root/MyProj_221_331_Zhakaris/
COPY *.h /root/MyProj_221_331_Zhakaris/
COPY *.pro /root/MyProj_221_331_Zhakaris/

RUN qmake exam_29_06.pro
RUN make

ENTRYPOINT ["./exam_29_06"]